# modify these according to the requirements
input_fits_path: "/path/to/input.fits" # simulated fits file
product_id: "le3.id.vmpz.output.poscatalog" 
data_model: "latest"  # Options: 'latest' OR '<specific_version>' (e.g. '9.2.3') OR '<path_to_file>' (e.g. 'raw/DataModel.xml')
fits_data_model: "latest" # Options: 'latest' OR '<specific_version>' (e.g. '9.2.3') OR '<path_to_file>' (e.g. 'raw/FitsDataModel.xml')
display_output: False

PAT: "<gitlab_personal_access_token>"  # GitLab personal access token with at least read permission