header.default.AutomatedValidationStatus: UNKNOWN
header.default.CreationDate: '2025-05-13T09:04:56.364Z'
header.default.Curator: Curator0
header.default.DataSetRelease: NA
header.default.EuclidPipelineSoftwareRelease: '0.0'
header.default.ExpirationDate: '2027-05-13T09:04:56.364Z'
header.default.ManualValidationStatus: UNKNOWN
header.default.PipelineDefinitionId: PipelineDefinitionId
header.default.PpoStatus: NA
header.default.ProdSDC: SDC-IT
header.default.ProductNotifiedToBeChecked: UNKNOWN
header.default.Published: '0'
header.default.Purpose: UNKNOWN
header.default.SoftwareName: NA
header.default.SoftwareRelease: '0.0'
header.default.ToBePublished: '0'
header.output.file: GenericHeader.xml
header.output.tag: Header
