fits_filepath: ./generated/EUC_LE3_PROXYSHEARCATALOG__20250515T154454.895944Z_00.00.fits
header.default.AutomatedValidationStatus: UNKNOWN
header.default.CreationDate: '2025-05-15T15:44:54.892Z'
header.default.Curator: Curator0
header.default.DataSetRelease: NA
header.default.EuclidPipelineSoftwareRelease: '0.0'
header.default.ExpirationDate: '2027-05-15T15:44:54.892Z'
header.default.ManualValidationStatus: UNKNOWN
header.default.PipelineDefinitionId: NA
header.default.PlanId: NA
header.default.PPOId: NA
header.default.PpoStatus: NA
header.default.ProdSDC: SDC-FR
header.default.ProductNotifiedToBeChecked: UNKNOWN
header.default.Published: '0'
header.default.Purpose: UNKNOWN
header.default.SoftwareName: NA
header.default.SoftwareRelease: '0.0'
header.default.ToBePublished: '0'
header.output.file: GenericHeader.xml
header.output.tag: Header
product_id: le3.id.vmpz.output.proxyshearcatalog
xml_filepath: ./generated/EUC_LE3_PROXYSHEARCATALOG__20250515T154454.895944Z_00.00.xml
